### ISSUE TITLE
create passcode for recruiter 

### ISSUE THREAD

**Issue by brianwang9100** [wdjg/coccareerfairapp-server#15]
create passcode field in employer
modify /register to convert given passcode to employer_id and only create recruiter user upon correct passcode.

maybe: create /employer/:id/passcode for retrieval (only authenticated recruiters can get this)

**Comment by jhayes45** [comment]
>create /employer/:id/passcode for retrieval (only authenticated recruiters can get this)
Will make a separate issue for this

**Comment by jhayes45** [comment]
Actually, don't need a separate route just for the passcode.

Have a recruiter use GET /employers/auth
