### ISSUE TITLE
verify that the QR cron job runs every 10mins (not 10 seconds)

### ISSUE THREAD

**Issue by jhayes45** [wdjg/coccareerfairapp-server#73]
per https://www.npmjs.com/package/node-cron , the seconds parameter is optional. Need to verify that I actually set the time parameter properly

**Comment by jhayes45** [comment]
per https://www.npmjs.com/package/node-cron , the seconds parameter is optional. Need to verify that I actually set the time parameter properly

**Comment by brianwang9100** [comment]
yeah, as of 2/21, master c5efa20 is doing it every 10 minutes. I think originally it was 10 seconds cause jesse and i were debugging whether it actually worked. That got into a commit and went through pull request review and i merged the changes. When I was deploying and checking heroku logs thats when I realized that it was 10 seconds just by seeing a lot of qr refreshes for the same company. I made the change and did a git commit --amend and force pushed master.
