### ISSUE TITLE
fix jwt to be the same on both login and registration

### ISSUE THREAD

**Issue by jhayes45** [wdjg/coccareerfairapp-server#94]

**Comment by brianwang9100** [comment]
why do they have to be the same? u just refresh the token and use the new one right?

**Comment by jhayes45** [comment]
Idk if they have to be the exact same but they both need to include the
user_type somebody

**Comment by jhayes45** [comment]
Somehow* and the procedure will likely not be the exact same to incorporate
the user type based on the code I looked at earlier

**Comment by jhayes45** [comment]
after some investigation, it looks like I might have a better handle on this after we merge the passcode thing since I also changed the registration logic for that issue

**Comment by jhayes45** [comment]
ok I think I was just being silly. The part of the jwt that differs is mostly the signature, which is unique to every jwt by nature of a signature. There are a couple of bytes that differ that are not part of the signature, but these can probably be explained by the differing expiry times, since we track expiry time down to the second.
